name: pytest
# Run all pytests in the test folder

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest rocrate
      - name: Test with pytest
        run: |
          pytest --tb=no -s
          git remote set-url origin ${{ secrets.ssh }}
          git status
          git add .
          git commit -m "Auto updating logging files"
          git push origin

